apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "github-arc-runner.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.autoscaling.minReplicas }}
  template:
    spec:
      {{- if .Values.organization }}
      organization: {{ .Values.organization }}
      {{- else if .Values.repository }}
      repository: {{ .Values.repository }}
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.scheduling.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.scheduling.tolerations | nindent 8 }}
      resources:
        {{- toYaml .Values.resources | nindent 8 }}
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: {{ .Release.Name }}-hpa
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "github-arc-runner.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ .Release.Name }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  scaleUpTriggers:
    {{- toYaml .Values.autoscaling.scaleUpTriggers | nindent 4 }}
  scaleDownTriggers:
    {{- toYaml .Values.autoscaling.scaleDownTriggers | nindent 4 }}