organization: ""
repository: "my-org/my-repo"
namespace: "actions-runner-system"

scheduling:
  nodeSelector:
    workload: "ci-cd-runners"
  tolerations:
    - key: "ci-cd-runners"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

autoscaling:
  minReplicas: 1
  maxReplicas: 10
  scaleUpTriggers:
    - duration: "2m"
  scaleDownTriggers:
    - duration: "10m"
      scaleDownFactor: "0.5"

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "2"
    memory: "4Gi"